theme: jekyll-theme-tactile
title: James Frowen
description: A collection of game development stuff.
author: James Frowen
lang: en_UK
twitter:
  username: JamesFrowenDev
google_analytics: UA-105767611-1
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag